services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
     - /home/ubuntu/running/logs:/program/logs
    environment:
     - NODE_ENV=production
    healthcheck:
      test: [ "CMD-SHELL", "curl http:/localhost:3000/api/hello" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=https://test.profresor.net
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
     - '9999:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    depends_on:
      api:
        condition: service_healthy
        restart: true
volumes:
  grafana_storage: