services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
     - /home/ubuntu/running/logs:/program/logs
    environment:
     - NODE_ENV=production
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=https://test.profresor.net
     - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    ports:
     - '9999:3000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
volumes:
  grafana_storage: